
services:
  postgres:
    container_name: postgres
    image: postgres:16
    volumes:
      - ./postgres_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
